apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # basic type : 가장 기본적인  secret type, TLS 관련 타입 등등 더 있다
data: # data 저장할 때 자동으로 secure하게 암호화되거나 하지 않음(basic securty default 아니므로). 무조건 base 64로 인코딩 필요 echo -n '인코딩할 문자열' | base64
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
